[2021-08-02 03:14:56,756] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: dag_1.running_script 2021-07-30T00:00:00+00:00 [queued]>
[2021-08-02 03:14:56,763] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: dag_1.running_script 2021-07-30T00:00:00+00:00 [queued]>
[2021-08-02 03:14:56,763] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-02 03:14:56,763] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-02 03:14:56,763] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-02 03:14:56,774] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): running_script> on 2021-07-30T00:00:00+00:00
[2021-08-02 03:14:56,778] {standard_task_runner.py:52} INFO - Started process 84179 to run task
[2021-08-02 03:14:56,790] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_1', 'running_script', '2021-07-30T00:00:00+00:00', '--job-id', '4', '--pool', 'default_pool', '--raw', '--subdir', '/Users/chuck/dev/DataEngineering.Labs.AirflowProject/airflow_home/dags/dag_1.py', '--cfg-path', '/var/folders/q4/t7100wbs1z91n0xw7n1xyynm0000gp/T/tmpzyecp3my', '--error-file', '/var/folders/q4/t7100wbs1z91n0xw7n1xyynm0000gp/T/tmpy1zzc2ci']
[2021-08-02 03:14:56,793] {standard_task_runner.py:77} INFO - Job 4: Subtask running_script
[2021-08-02 03:14:56,837] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_1.running_script 2021-07-30T00:00:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2021-08-02 03:14:56,874] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag_1
AIRFLOW_CTX_TASK_ID=running_script
AIRFLOW_CTX_EXECUTION_DATE=2021-07-30T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-30T00:00:00+00:00
[2021-08-02 03:14:56,915] {logging_mixin.py:104} WARNING - /Users/chuck/dev/DataEngineering.Labs.AirflowProject/airflow_home//dags/package/graph_points_gained_during_season.py:17 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2021-08-02 03:14:56,923] {logging_mixin.py:104} WARNING - /Users/chuck/dev/DataEngineering.Labs.AirflowProject/airflow/lib/python3.9/site-packages/pandas/core/indexing.py:1817 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2021-08-02 03:14:56,933] {logging_mixin.py:104} WARNING - /Users/chuck/dev/DataEngineering.Labs.AirflowProject/airflow_home//dags/package/graph_points_gained_during_season.py:23 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2021-08-02 03:14:59,641] {python.py:151} INFO - Done. Returned value was: None
[2021-08-02 03:14:59,838] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=dag_1, task_id=running_script, execution_date=20210730T000000, start_date=20210802T071456, end_date=20210802T071459
[2021-08-02 03:14:59,977] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-02 03:15:00,216] {local_task_job.py:149} INFO - Task exited with return code 0
